FROM node:22-alpine3.19

WORKDIR /app

COPY ./lpr/package.json .

COPY ./lpr .

# RUN npm install

RUN yarn

# RUN npm i react-router-dom

#RUN npm install react-transition-group


EXPOSE 5173 

CMD [ "npm" , "run" , "dev" , "--" , "--host" ]
