FROM node:22-alpine3.19

WORKDIR /app

COPY ./lpr_manage/package.json .

COPY ./lpr_manage .

# RUN npm install

RUN yarn

# RUN npm i react-router-dom

#RUN npm install react-transition-group
RUN yarn add axios


EXPOSE 5173 

CMD [ "npm" , "run" , "dev" , "--" , "--host" ]
